apiVersion: v1
kind: Pod
metadata:
  name: config-secret-volume-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c", "echo 'Hello from Pod' > /data/hello.txt; sleep 30"]
      volumeMounts:
        - name: secret-vol
          mountPath: /data/volume/secret
        - name: configmap-vol
          mountPath: data/volume/configmap
  volumes:
    - name: secret-vol
      secret:
        secretName: my-sc-vol
    - name: configmap-vol
      configMap:
        Name: my-cm-vol
      