apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proj1
  template:
    metadata:
      labels:
        app: proj1
    spec:
      containers:
        - name: proj1
          image: yourdockerhubusername/proj1:latest
          ports:
            - containerPort: 5000