apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proj1-ing
spec:
  ingressClassName: nginx
  rules:
    - host: proj1.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proj1-svc
                port:
                  number: 80