apiVersion: apps/v1
kind: Deployment
metadata:
  name: first_deployment
spec:
  replicas: 2
  selector:
    matchLabel:
      # equality based label selector
      app: nginx  # This can also be --> app=nginx
      environment: dev # This can also be --> environment=dev
  template:
    metadata:
      name: testpod
      label:
        app: nginx  
        environment: dev #
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
