apiVersion: apps/v1
kind: Deployment
metadata:
  name: first_deployment
spec:
  replicas: 2
  selector:
    matchLabel:
      app: dev
  template:
    metadata:
      name: testpod
      label:
        app: dev
    spec:
      containers:
      - name: co1
        image: ubuntu
        ports:
        - containerPort: 80
